server:
  port: 8080

onboarding:
  task-queue: OnboardingTaskQueue-${HOSTNAME}
  service:
    address: http://localhost:8090

spring:
  temporal:
    connection:
      namespace: default
      target: localhost:7233
    workers:
      - name: onboarding-worker
        task-queue: ${onboarding.task-queue}
    workersAutoDiscovery:
      packages:
        - org.acme.patient.onboarding.app.workflows
        - org.acme.patient.onboarding.app.activities
