server:
  port: 8080

onboarding:
  task-queue: OnboardingTaskQueue
  service:
    address: http://localhost:8090

spring:
  temporal:
    connection:
      namespace: default
      target: localhost:7233
    workers:
      - task-queue: ${onboarding.task-queue}
        workflow-classes:
          - org.acme.patient.onboarding.app.workflows.OnboardingWorkflowImpl
        activity-beans:
          - onboardingActivitiesImpl
